# Site settings
title: Jeremy White
subtitle: Senior Mobile Developer
email: jeremy.ro.white@gmail.com
username: iheart2code
description: "I serve as a switch hitter, providing expertise in iOS, Android, and web development as well as serving in a senior role. I am currently focusing my efforts on iOS development and leading Idean's mobile team."
baseurl: ""
url: "https://thejeremywhite.com"
enforce_ssl: thejeremywhite.com

# Collections
collections: 
  blog:
    output: true
    permalink: /:collection/:path.html
  work:
    output: true
    permalink: /:collection/:path.html

# Build settings
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- bower.json
- CNAME
